# Generated by Django 6.0.3 on 2026-03-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('history', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_start', models.DateField(help_text='Даатгал эхлэх огноо')),
                ('coverage_end', models.DateField(help_text='Даатгал дуусах огноо')),
                ('last_payment_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_balance',
            },
        ),
        migrations.CreateModel(
            name='CustomerIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Жишээ нь: Тээврийн хэрэгсэл', max_length=100)),
                ('name', models.CharField(help_text='Жишээ нь: КАСКО даатгал', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Жишээ нь: 🚗', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Идэвхтэй зардаг эсэх')),
            ],
            options={
                'db_table': 'support_insuranceproduct',
            },
        ),
    ]
