# Generated by Django 6.0.3 on 2026-03-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_pdfupload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerbalance',
            table='customer_balance',
        ),
    ]
