# Generated by Django 6.0.3 on 2026-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_contract_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationstate',
            name='awaiting_contract',
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
