# Generated by Django 6.0.3 on 2026-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_remove_conversationstate_awaiting_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Бүтээгдэхүүний нэр')),
                ('start_date', models.DateField(verbose_name='Эхэлсэн огноо')),
                ('end_date', models.DateField(verbose_name='Эрх дуусах огноо')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компанийн нэр')),
                ('company_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регистрийн дугаар')),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFUpload',
        ),
    ]
